import "bootstrap/dist/css/bootstrap.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/lib/nav";
import Footer from "@/lib/footer";

import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        {/* <Row lg={8} md={8} sm={12} > */}
        {children}
        {/* </Row> */}
        <Footer />
      </body>
    </html>
  );
}
